version: "3.7"
services:
  gethexporter:
    image: hunterlong/gethexporter
    ports:
      - "6061:9090"
    env_file:
      - .env
    
  prometheus:
    image: prom/prometheus
    depends_on:
      gethexporter:
        condition: service_started
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - ./grafana.db:/var/lib/grafana/grafana.db